# Config server
server:
  port: 8088

# Config to spring file
spring:
  # config to use .env file
  config:
    import: optional:file:.env[.properties]

  # config database mongodb
  data:
    mongodb:
      database: ${MONGO_DATABSE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  sendgrid:
    api-key: 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
# Set level log default
logging:
  level:
    root: info
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
